apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: conversion-pulse
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres-statefulset.yaml
  - api-deployment.yaml
  - api-service.yaml
  - hpa.yaml
  - ingress.yaml
