apiVersion: v1
kind: Secret
metadata:
  name: cpulse-db-secret
  namespace: conversion-pulse
type: Opaque
stringData:
  POSTGRES_USER: cpulse
  POSTGRES_PASSWORD: changeme
  POSTGRES_DB: cpulse
  DATABASE_URL: postgres://cpulse:changeme@cpulse-db.conversion-pulse.svc.cluster.local:5432/cpulse
