global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: conversion-pulse-api
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets: ["api:3000"]

  - job_name: conversion-pulse-worker
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets: ["worker:9101"]

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
